In [2]:
import numpy as np
from scipy import misc

##2
arreglo_ceros = np.zeros(10)
print(arreglo_ceros)

##3
a = np.zeros(5)
b = np.ones(5)
arreglo_ceros_unos = np.concatenate((a,b),axis=0)
print(arreglo_ceros_unos)

##4
c = np.arange(1,51)
arreglo_50 = c[::-1]
print(arreglo_50)

##5
matriz1 = np.arange(9).reshape(3,3)
print(matriz1)

##6
arreglo = [1,2,0,0,4,0]
res = []
for index,i in enumerate(arreglo):
    if i == 0:
        res.append(index)
print(res)

##7
matriz_identidad = np.eye((3))
print(matriz_identidad)

##8
random = np.random.rand(3,3,3)*10
print(random)

##9
matriz_buscar = np.random.rand(10,10)*10
print(matriz_buscar)
print('minimo valor: ')
print(matriz_buscar.min())
print('mayor valor: ')
print( matriz_buscar.max())

##10
mapache = misc.face()
import matplotlib.pyplot as plt
plt.imshow(mapache)
##print(lista_colores)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2, 3, 5]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[[0.12617017 0.30589839 8.37089222]
  [8.3459219  3.37841077 0.70126147]
  [8.84355475 4.08114618 4.2359466 ]]

 [[0.0351717  8.50417095 8.89590465]
  [7.29254313 4.64268254 1.41465792]
  [7.82321547 0.16746212 5.46653797]]

 [[7.43412896 5.85900206 1.5965351 ]
  [5.14073655 0.54714757 8.5624972 ]
  [0.13588978 7.00357739 0.59910895]]]
[[1.07851578e+00 8.10777015e+00 4.57706983e+00 5.49569454e+00
  6.63530923e+00 8.73117763e+00 4.36480312e+00 5.97822313e+00
  2.02710012e+00 6.95503260e+00]
 [1.26798506e+00 7.73241792e-01 1.23225271e+00 7.57303172e+00
  9.31809003e+00 6.07484685e+00 8.26195348e-01 8.28841787e+00
  5.86718226e+00 4.20739864e+00]
 [6.53348360e+00 2.82144494e+00 9.42940749e-01 4.70739

<function matplotlib.pyplot.imshow(X, cmap=None, norm=None, aspect=None, interpolation=None, alpha=None, vmin=None, vmax=None, origin=None, extent=None, shape=None, filternorm=1, filterrad=4.0, imlim=None, resample=None, url=None, hold=None, data=None, **kwargs)>